=== mingogo/YDesignEndeca/endeca-app/YDesignStores/designer-flat-dimension-build-utility/input/dimensions.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Copyright (c) 2001-2003, Endeca Technologies, Inc. All rights reserved.
-->

<!ENTITY % common.dtd SYSTEM "common.dtd">
%common.dtd;
<!ELEMENT DIMENSIONS (NUM_DVALS?, DIMENSION*)>
<!ATTLIST DIMENSIONS
	VERSION CDATA #IMPLIED
>

<!ELEMENT NUM_DVALS (#PCDATA)>

<!ELEMENT DIMENSION (DIMENSION_ID, DIMENSION_NODE)>
<!ATTLIST DIMENSION
	NAME CDATA #IMPLIED
	SRC_TYPE (INTERNAL | PROPMAPPER | AUTOGEN | EXTERNAL) #IMPLIED
	SRC_FILE CDATA #IMPLIED
>

<!ELEMENT DIMENSION_NODE (DVAL, DIMENSION_NODE*)>

<!--
    DVAL TYPE="DVAL" is depricated; use EXACT instead.
-->
<!ELEMENT DVAL (DVAL_ID, SYN+, LBOUND?, UBOUND?, PROP*)>
<!ATTLIST DVAL
	TYPE (EXACT | RANGE | LEVEL | SIFT | DVAL) #REQUIRED
>
<!ELEMENT LBOUND (BOUND)>
<!ELEMENT UBOUND (BOUND)>
<!ELEMENT BOUND EMPTY>
<!ATTLIST BOUND
	TYPE (STRING | INTEGER | FLOAT | CURRENCY | DATE) #REQUIRED
	VALUE CDATA #REQUIRED
	CLOSURE (OPEN | CLOSED) #REQUIRED
>
<!ELEMENT SYN (#PCDATA)>
<!ATTLIST SYN
	DISPLAY (TRUE | FALSE) #REQUIRED
	SEARCH (TRUE | FALSE) #REQUIRED
	CLASSIFY (TRUE | FALSE) #REQUIRED
>

=== mingogo/YDesignEndeca/endeca-app/YDesignStores/config/pipeline/dimensions.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE DIMENSIONS SYSTEM "dimensions.dtd">
<DIMENSIONS VERSION="1.0.0">

  <DIMENSION NAME="Brand" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="1"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="1"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Brand</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="ShipsToCanada" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">ShipsToCanada</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Exclusive" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="6"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="6"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Exclusive</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="New" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="7"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="7"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">New</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Category_id" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000485"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000485"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Category_id</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Collection" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000486"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000486"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Collection</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Color" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000487"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000487"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Color</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Customer_ratings" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000488"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000488"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Customer_ratings</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Designer" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000489"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000489"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Designer</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Gift_wrap" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000490"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000490"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Gift_wrap</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Lamp_type" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000491"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000491"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Lamp_type</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Other_features" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000492"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000492"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Other_features</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Seat_features" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000493"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000493"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Seat_features</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Store_id" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000494"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000494"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Store_id</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Table_features" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000495"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000495"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Table_features</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Warehouse_sale" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000496"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000496"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Warehouse_sale</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="BrandForCategories" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000497"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000497"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">BrandForCategories</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Is_free_shipping" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000498"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000498"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Is_free_shipping</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Is_new" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000499"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000499"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Is_new</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Is_on_sale" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000500"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000500"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Is_on_sale</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Quick_ship" SRC_TYPE="AUTOGEN">
    <DIMENSION_ID ID="2000502"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="2000502"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Quick_ship</SYN>
      </DVAL>
    </DIMENSION_NODE>
  </DIMENSION>

  <DIMENSION NAME="Price Range" SRC_TYPE="INTERNAL">
    <DIMENSION_ID ID="4000010"/>
    <DIMENSION_NODE>
      <DVAL TYPE="EXACT">
        <DVAL_ID ID="4000010"/>
        <SYN CLASSIFY="FALSE" DISPLAY="TRUE" SEARCH="FALSE">Price Range</SYN>
      </DVAL>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000012"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$501 - $1000</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="501"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="1000"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000013"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$1001 - $1500</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="1001"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="1500"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000011"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">0 - $500</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="0"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="500"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000014"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$1501 - $2000</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="1501"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="2000"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000015"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$2001 - $2500</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="2001"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="2500"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000016"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$2501 - $3000</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="2501"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="3000"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000017"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$3001 - $3500</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="3001"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="3500"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000018"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$3501 - $4000</SYN>
          <LBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="3501"/>
          </LBOUND>
          <UBOUND>
            <BOUND CLOSURE="CLOSED" TYPE="FLOAT" VALUE="4000"/>
          </UBOUND>
        </DVAL>
      </DIMENSION_NODE>
      <DIMENSION_NODE>
        <DVAL TYPE="RANGE">
          <DVAL_ID ID="4000019"/>
          <SYN CLASSIFY="TRUE" DISPLAY="TRUE" SEARCH="TRUE">$4001 - $4500</SYN>
          <LBOUND>
